### ISSUE TITLE
Support for ESLint 8.0.0

### ISSUE THREAD

**Issue by ldrick** [jonaskello/eslint-plugin-functional#278]
# Suggestion
ESLint 8.0.0 dropped and brings some breaking changes.
https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0
Yesterday @typescript/eslint also published 5.0.0 to support new ESLint version.
https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.0.0

From the errors thrown, I see at least this dependency should be updated to support new ESLint:
"@typescript-eslint/experimental-utils"

Currently I am getting this error:

```
yarn lint

Oops! Something went wrong! :(

ESLint: 8.0.0

TypeError: Failed to load plugin 'functional' declared in 'package.json#overrides[1]': Class extends value undefined is not a constructor or null
Referenced from: [my]\package.json
    at Object.<anonymous> ([my]\.yarn\__virtual__\@typescript-eslint-experimental-utils-virtual-7774eb0b8d\0\cache\@typescript-eslint-experimental-utils-npm-4.28.1-ab919abf02-34a0dd8230.zip\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\CLIEngine.js:12:34)
    at Module._compile ([my]\.yarn\cache\v8-compile-cache-npm-2.1.1-efff1ef0a4-692f6bc698.zip\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.external_module_.Module._load [my]\.pnp.cjs:20312:14)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require ([my]\.yarn\cache\v8-compile-cache-npm-2.1.1-efff1ef0a4-692f6bc698.zip\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> ([my]\.yarn\__virtual__\@typescript-eslint-experimental-utils-virtual-7774eb0b8d\0\cache\@typescript-eslint-experimental-utils-npm-4.28.1-ab919abf02-34a0dd8230.zip\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\index.js:14:14)
    at Module._compile ([my]\.yarn\cache\v8-compile-cache-npm-2.1.1-efff1ef0a4-692f6bc698.zip\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

Whether or not this implies the requirement of a new major release, I am not aware.

**Comment by RebeccaStevens** [comment]
Thanks for the offer but I'm working on this atm. There should be a release later today.

**Comment by m4thieulavoie** [comment]
> Thanks for the offer but I'm working on this atm. There should be a release later today.

Sorry I should've checked in the issue first, just closed my PRs. Thanks for looking into it 👍

**Comment by RebeccaStevens** [comment]
I've just released an RC version of the next version of this plugin which has support eslint 8 ([this PR](https://github.com/jonaskello/eslint-plugin-functional/pull/227)). Please feel free to test it out and if all is well, I'll release it in the next day or so.
